definitions:
  dto.Login:
    properties:
      password:
        description: 密码
        example: "123456"
        type: string
      username:
        description: 用户名
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  handler.Response:
    properties:
      code:
        type: string
      data:
        type: object
      message:
        type: string
    type: object
info:
  contact: {}
  description: Golang 脚手架
  license: {}
  title: go-scaffold/
  version: 1.0.0
paths:
  /api/login:
    post:
      description: 登陆成功后，签发一个15分钟效期的cookie，用于后端鉴权
      parameters:
      - description: 用户登陆信息
        in: body
        name: arg
        required: true
        schema:
          $ref: '#/definitions/dto.Login'
      responses:
        "200":
          description: 返回结果：{code:2000,message:"Success",data:nil}
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 登录
      tags:
      - 授权
  /api/logout:
    get:
      responses:
        "200":
          description: 返回结果：{code:2000,message:"Success",data:nil}
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 登出
      tags:
      - 授权
schemes:
- http
swagger: "2.0"
