[app]
machine_id = 1                  # 机器id

# grpc服务相关配置信息
[app.grpc]
network = "tcp"                 # 服务网络协议
addr = "127.0.0.1:3000"         # 服务地址
scheme = "scaffold"             # 服务scheme
name = "ping"                   # 服务名称

# etcd注册机相关配置信息
[app.grpc.register.etcd]
endpoints = ["127.0.0.1:2379"]  # 注册机地址
dial_timeout = "5s"             # 拨号超时（单位：秒）
heartbeat_cycle = "5s"          # 心跳周期（单位：秒）
lease_ttl = "5s"                # 租约时长（单位：秒）

# mysql相关配置信息
[app.mysql.db1]
dsn = "root:root@tcp(127.0.0.1:3306)/db1?charset=utf8&parseTime=True&loc=Local"
max_idle_conns = 50         # 最大空闲连接数
max_open_conns = 100        # 最大活动连接数
conn_max_lifetime = "300s"  # 连接的最大存活时间

# mysql相关配置信息
[app.mysql.db2]
dsn = "root:root@tcp(127.0.0.1:3306)/db2?charset=utf8&parseTime=True&loc=Local"
max_idle_conns = 50         # 最大空闲连接数
max_open_conns = 100        # 最大活动连接数
conn_max_lifetime = "300s"  # 连接的最大存活时间

# redis相关配置信息
[app.redis.0]
addr = "127.0.0.1:6379"
password = ""
db = 0

# redis相关配置信息
[app.redis.1]
addr = "127.0.0.1:6379"
password = ""
db = 0

# log相关配置信息
[app.log]
dir = "."                       # 日志存放目录
name = "http.log"               # 日志名称
level = "info"                  # 日志级别
debug = true                    # 是否记录debug日志
max_size = 100                  # 日志文件大小（单位：MB）
max_age = 5                     # 备份时间（单位：天
max_backups = 7                 # 备份数量
compress = false                # 是否压缩日志